stages:
  - build
  - push
  - deploy

variables:
  DOCKER_REGISTRY: "docker.io"
  DOCKER_IMAGE: "dhineshpandian/argocdtest" 
  IMAGE_TAG: "$CI_COMMIT_REF_NAME" 

before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

build:
  stage: build
  script:
    - docker build -t $DOCKER_REGISTRY/$DOCKER_IMAGE:$IMAGE_TAG .
  only:
    - main
    - develop

push:
  stage: push
  script:
    - docker push $DOCKER_REGISTRY/$DOCKER_IMAGE:$IMAGE_TAG
  only:
    - main
    - develop

deploy:
  stage: deploy
  script:
    - |
      # Apply the deployment files for either blue or green version
      if [[ "$CI_COMMIT_REF_NAME" == "main" ]]; then
        # Assuming `main` branch deploys the new version
        kubectl apply -f k8s/deployment-blue.yaml  # Deploy Blue
        kubectl patch service argocd-service -p '{"spec": {"selector": {"app": "argocd", "version": "blue"}}}'
      fi
  only:
    - main
