stages:
  - build
  - push
  - deploy

variables:
  DOCKER_REGISTRY: "docker.io"
  DOCKER_IMAGE: "<username>/django-todo-app" 
  IMAGE_TAG: "$CI_COMMIT_REF_NAME" 

before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

build:
  stage: build
  script:
    - docker build -t $DOCKER_REGISTRY/$DOCKER_IMAGE:$IMAGE_TAG .
  only:
    - main
    - develop

push:
  stage: push
  script:
    - docker push $DOCKER_REGISTRY/$DOCKER_IMAGE:$IMAGE_TAG
  only:
    - main
    - develop

deploy:
  stage: deploy
  script:
    - kubectl apply -f k8s/deployment-blue.yaml
    - kubectl apply -f k8s/service.yaml
  only:
    - main
