apiVersion: v1
kind: Service
metadata:
  name: argocd-service
spec:
  selector:
    app: argocd
    version: blue  
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer  
